# Generated by Django 2.1 on 2018-08-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete='CASCADE', related_name='commentss', to='wall.Message')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='comments', to='wall.User')),
            ],
        ),
    ]
